### ISSUE TITLE
Doesn't work when the meaning is not described with the word "means"

### ISSUE THREAD

**Issue by henryso** [mackorone/tidbyt-word-of-the-day#1]
When https://merriam-webster.com/word-ot-the-day describes the meaning of a word with "is" or "refers to" rather than "means", the render will fail with an error.

See https://www.merriam-webster.com/word-of-the-day/carte%20blanche-2021-12-29 and https://www.merriam-webster.com/word-of-the-day/zeitgeist-2021-12-31

**Comment by henryso** [comment]
Also see https://www.merriam-webster.com/word-of-the-day/jubilate-2021-12-25 and https://www.merriam-webster.com/word-of-the-day/astute-2021-12-30 for some other variants that throw the algorithm into a bit of a tizzy.

**Comment by mackorone** [comment]
@henryso, thanks for the report! You're absolutely right - the regex was unnecessarily strict. Fixed in bff0eded4d06a1e89954bc8a3fb5bd1e7316f1b5.

**Comment by henryso** [comment]
@mackorone That regex chops off the final double quote in today's word: https://www.merriam-webster.com/word-of-the-day/captious-2022-01-02

**Comment by mackorone** [comment]
Good catch. I just updated the regex again, hopefully that works for now.
